main page markup
htmlacademy-htmlcss/581243-technomart-29 pull request #2
Opened 2020-09-11 21:49 UTC by vrnvgasu

2020-09-12 13:11 UTC, mkolotovich requested changes

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +          Мы можем доставить ваш товар в самые отдаленные точки России!<br>
Удаляй br, он лишний. Перенесем через стили.

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +          Вы можете забрать товар сами,<br>
Удаляй br, он лишний. Перенесем через стили.

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +        </p>
Это параграфа нет в макете), удаляй его.

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      <h2>Контакты</h2>
Задай заголовку класс visually hidden

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      <a>ТЕХНОМАРТ</a>
Логотип делается с помощью изображения, даже если он состоит из текста. Экспортируй свг из макета и вставь его внутрь ссылки вместо текста

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +        г. Санкт-Петербург, ул. Б. Конюшенная, д. 19/8<br>
Удаляй br, он лишний. Перенесем через стили.

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +        +7 (812) 555-05-55
Согласно критерию Д29 - Телефоны размечены ссылками с протоколом tel.(https://up.htmlacademy.ru/htmlcss/29/criteries#d29)

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      <h2>Карта сайта</h2>
Задай заголовку класс visually hidden

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      © 2010–2019 Компания «Техномарт»<br>Все права защищены
Удаляй br, он лишний. Перенесем через стили.

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      <h2>Давайте дружить!</h2>
Задай заголовку класс visually hidden

2020-09-12 13:11 UTC, mkolotovich commented on index.html
> +      <a href="https://htmlacademy.ru">htmlacademy.ru</a>
Согласно ТЗ 3.5 - Ссылка в подвале htmlacademy.ru ведёт на лендинг интенсива «HTML и CSS. Профессиональная вёрстка сайтов»(https://up.htmlacademy.ru/htmlcss/29/project/technomart#technomart-3-5)

2020-09-12 17:02 UTC, vrnvgasu commented on index.html
> +        <a>ТЕХНОМАРТ</a>
Поставил заглушку https://via.placeholder.com/220x47
Графику еще не нарезали из макет

2020-09-12 17:04 UTC, vrnvgasu commented on index.html
> +        <input type="search">
Пока в label написал "Поиск". Так понимаю, что потом надо будет заменить слово на иконку

2020-09-13 11:31 UTC, mkolotovich commented on index.html
> +        <input type="search">
Тут бы я немного по другому сделал. Я бы обернул в label input, а также добавил внутрь label свг иконку и спозиционировал бы ее потом, а текст label бы потом скрыл через стили.

2020-09-13 11:36 UTC, mkolotovich commented on index.html
> +            <figcaption>Настоящие мужские игрушки</figcaption>
Вынеси параграф на уровень вверх из figure, чтобы он оказался в div вместе с заголовком и закрой тег div сразу после параграфа.

2020-09-14 12:56 UTC, mkolotovich commented on index.html
>            </p>
Ты пропустил элемент - ОТПРАВИТЬ ЗАЯВКУ. Добавь его и мердж

2020-09-14 12:57 UTC, mkolotovich requested changes
Одно исправление и мердж

2020-09-14 14:15 UTC, mkolotovich commented on index.html
> +          <button type="button">Дрели</button>
Это размечается через input type="radio"

2020-09-14 14:15 UTC, mkolotovich requested changes
Честное слово последнее замечание)

2020-09-14 21:13 UTC, merged