верстка catalog
htmlacademy-htmlcss/581243-technomart-29 pull request #3
Opened 2020-09-15 08:02 UTC by vrnvgasu

2020-09-16 09:52 UTC, mkolotovich requested changes
Добавь на главной странице ссылки на внутреннюю.

2020-09-16 09:52 UTC, mkolotovich commented on catalog.html
> +      </div>
Такой блок должен находиться внутри каждой карточки товара. По умолчанию должен быть скрыт и появляться при наведении курсора мыши.

2020-09-16 09:52 UTC, mkolotovich commented on catalog.html
> +        В ассортиментном ряду есть выбор «трехрежимников»: в одном устройстве будут совмещены отбойный молоток и ударная дрель.<br>
Вот эти br удали они лишние. Перенос сделаем через стили.

2020-09-16 09:52 UTC, mkolotovich commented on catalog.html
> +      Разработано -
Здесь по макету тире, а не дефис

2020-09-17 14:26 UTC, vrnvgasu commented on catalog.html
> +      </div>
Перенес в карточку товара (+ на главной). Порядок:

Картинка,

блок купить/в закладки

Название товара

старая цена

новая цена

2020-09-18 06:24 UTC, mkolotovich requested changes
Исправь одно замечание с предыдущей проверки и мердж

2020-09-18 12:20 UTC, merged