стили для главной
htmlacademy-htmlcss/581243-technomart-29 pull request #4
Opened 2020-09-20 06:29 UTC by vrnvgasu

2020-09-21 07:52 UTC, mkolotovich requested changes
Исправь замечания

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +  color: var(--white);
Измени на #F1F5F7;

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +  font-style: normal;
Задай color: #F3F7F9;

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .footer-promo-list li:nth-child(2) a и задай ему color: #FFDA96;

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .main-navigation и задай ему background: rgba(0, 0, 0, 0.01);

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--basic-grey-darkest);
Измени на rgba(0, 0, 0, 0.25);

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +
Создай селектор .search:focus::placeholder и задай ему color: #000000;

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--header-panel);
Измени на #1D2739

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +  background: none;
Измени на rgba(255,255,255,0.3)

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +
Создай селекторы для .promo-button для наведения и клика и задай им стили как на макете

2020-09-21 07:52 UTC, mkolotovich commented on css/style.css
> +.slider-button:hover, .slider-button:active {
Убери из правила .slider-button:active и создай для него отдельный селектор. Селектору .slider-button:active задай background: #BA2732;

2020-09-22 12:24 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--success);
Не исправлено

2020-09-22 12:33 UTC, mkolotovich commented on css/style.css
> +  background-color: var(--header-panel);
Удали свойство opacity: 0.5; и задай color: rgba(255,255,255,0.5);

2020-09-22 12:38 UTC, mkolotovich requested changes
Исправь 2 замечания с предыдущей проверки и мердж

2020-09-22 15:13 UTC, vrnvgasu commented on css/style.css
> +  background-color: var(--success);
поправил

2020-09-23 06:06 UTC, merged